# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd626da56a5c98c4241bea3f142b270dd36b978a13b628539eaf23f0646a58ce8d86f7e0dbb0db92c7e109cd9b99695e5f3d623f19b78bed55d4a05f3f4b8ed5

test:
  secret_key_base: 5dce658221f3c330567ac462b2e06a2474afa4a830d853073514d55498db64170c3ac254a29a562045a2b61a6cc2925d86f9764627f640a1117b071c363129d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
